version: "3"
services:
    mongodb:
        image: mongo
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - ./data:/db
        env_file:
            - .env
        depends_on:
            - mongo-import
        networks:
            - mynetwork
   
    mongo-import:
        image: mongo
        container_name: mongo_import
        volumes:
            - ./data:/data
        command: mongoimport --host mongodb --db $MONGO_DATABASE --collection $MONGO_COLLECTION --file /data/verzeichnis.json --jsonArray
        networks:
            - mynetwork
   
    backend:
        container_name: Express-Server

        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - mongodb
        networks:
            - mynetwork
        command: node server.js   # Startbefehl für den Express-Server
networks:
    mynetwork: